//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Misc/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""ControlBinds"",
            ""id"": ""4403b557-3a14-480c-a6a7-4a11ff060794"",
            ""actions"": [
                {
                    ""name"": ""KeyboardLStick"",
                    ""type"": ""Value"",
                    ""id"": ""681d4396-9d31-4cb9-b873-3e20851afd5c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyboardEnter"",
                    ""type"": ""Button"",
                    ""id"": ""b95a8fb0-282a-4b96-bfaf-7936e0fb24f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardLShift"",
                    ""type"": ""Button"",
                    ""id"": ""eb443323-f164-4b65-8cce-3f6bf0dff4e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardEscape"",
                    ""type"": ""Button"",
                    ""id"": ""c3d3660d-ca65-45e4-958c-85578b0be5c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardSpace"",
                    ""type"": ""Button"",
                    ""id"": ""273c64ee-47bf-470e-bfb8-3c759910ed79"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardQ"",
                    ""type"": ""Button"",
                    ""id"": ""2c7922f8-ea4d-49c7-b6b3-5ff48c37cec6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardE"",
                    ""type"": ""Button"",
                    ""id"": ""26cba126-39b3-451f-ab7e-69235c737223"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardR"",
                    ""type"": ""Button"",
                    ""id"": ""dd74b1fc-8d35-4bcd-a414-162f04b44663"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XboxA"",
                    ""type"": ""Button"",
                    ""id"": ""5911d84b-dff0-4a16-b0fa-7c7e60574798"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XboxB"",
                    ""type"": ""Button"",
                    ""id"": ""3db59712-8825-43ed-b957-62a3faa9dcd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XboxX"",
                    ""type"": ""Button"",
                    ""id"": ""6075925e-166b-4f92-a8e5-7cf43442bf44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XboxY"",
                    ""type"": ""Button"",
                    ""id"": ""7a2d5aac-f65d-41ae-bc06-7da47b1b63b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XboxLStick"",
                    ""type"": ""Value"",
                    ""id"": ""e123b515-2921-4c83-899b-abf2726eb97b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""XboxView"",
                    ""type"": ""Button"",
                    ""id"": ""815fd397-c8a4-4771-9065-58aab1bd1f74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XboxMenu"",
                    ""type"": ""Button"",
                    ""id"": ""2bed1d4a-407d-46db-a038-a91cca739da3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchA"",
                    ""type"": ""Button"",
                    ""id"": ""5a4b2c64-a3fb-466b-aadb-fe5d6058cb8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchB"",
                    ""type"": ""Button"",
                    ""id"": ""5ba0c5bf-2787-4b58-a2f0-51d0c6df5fad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchX"",
                    ""type"": ""Button"",
                    ""id"": ""ef49ea55-10bf-4d03-9648-480ec3fa0b2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchY"",
                    ""type"": ""Button"",
                    ""id"": ""b2bb67f2-6178-456f-bc6c-4269c392eba2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLStick"",
                    ""type"": ""Value"",
                    ""id"": ""6da64235-318f-45b5-8c74-323c39431ceb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchMinus"",
                    ""type"": ""Button"",
                    ""id"": ""4f2076bb-d9f7-44ae-a3ce-c5a0a71cc19d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchPlus"",
                    ""type"": ""Button"",
                    ""id"": ""7554220c-e3a4-43a7-ba43-866bf0074849"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WebLStick"",
                    ""type"": ""Value"",
                    ""id"": ""c65087b5-7eb5-44f8-bfa8-36b56d1e5f24"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WebEast"",
                    ""type"": ""Button"",
                    ""id"": ""1994fea0-040a-49cd-bfe3-2d50d7fccb62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WebSouth"",
                    ""type"": ""Button"",
                    ""id"": ""53fd059b-dc2b-4ab7-94b7-eb02014fbc7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WebNorth"",
                    ""type"": ""Button"",
                    ""id"": ""62bee77f-6948-4be6-8538-c2a793ab6713"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WebWest"",
                    ""type"": ""Button"",
                    ""id"": ""3050b210-cd79-432b-8b28-63ec58f1ef9e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WebLShoulder"",
                    ""type"": ""Button"",
                    ""id"": ""365345f3-c224-434e-8820-09a94035e25a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WebRStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""6eac63a1-000a-4e29-be17-b3d487bf55b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WebSelect"",
                    ""type"": ""Button"",
                    ""id"": ""407d6aad-eb80-4685-a5b2-647f4b1c32d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WebLStickUpwards"",
                    ""type"": ""Button"",
                    ""id"": ""fb1cf2e6-2dd7-46b5-90ee-46fc15b2d527"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationLStick"",
                    ""type"": ""Value"",
                    ""id"": ""4e5e6948-f4cb-4613-94eb-cf2af2b9a92a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlaystationCross"",
                    ""type"": ""Button"",
                    ""id"": ""8f642364-c698-492a-b76d-28862965e2cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationTriangle"",
                    ""type"": ""Button"",
                    ""id"": ""7c8d8d1c-3b82-42e9-89bf-b76c772559fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationCircle"",
                    ""type"": ""Button"",
                    ""id"": ""9afde248-c277-4ab0-a03e-b1db83d3324b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationSquare"",
                    ""type"": ""Button"",
                    ""id"": ""7578e5f0-7d5f-4cf8-8725-55aed2d45b09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationShare"",
                    ""type"": ""Button"",
                    ""id"": ""a32d01e0-87a4-45f4-bbf9-c07277bf796c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationOptions"",
                    ""type"": ""Button"",
                    ""id"": ""9fbe711c-f5a5-4d57-a0df-84cf9411e445"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4a9e7eb0-b785-4b85-ac9e-e63fb6c05b15"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardEnter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3108841-e9a7-40d2-91ac-177c46d323c1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardLShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""431e478a-e95e-4cc3-a569-ea6ac410ec95"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardLStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b8f184c2-4f78-42b1-8b4a-56434abddf82"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardLStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3358a8e1-1932-4069-8ecd-c88863cc7a2e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardLStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""17835ece-da8d-49e0-bbde-73cdfa21f7c5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardLStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ce830dc0-de5d-4cb9-9a14-4dba2bd6a1e8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardLStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""28e3f88b-728b-4173-a00e-af575d1fa245"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardSpace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb2689ee-2e50-4fd3-b24c-2c93423d7587"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardQ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cfc6ae2-6165-4d5e-89c5-887c3296b3e0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d8394ec-9933-408b-a8d2-ebeb07be3a86"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9db5f462-c0d1-4cb1-a47d-f9e0f6811cc1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""KeyboardEscape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""132b8a31-72de-4425-9a2d-099563218489"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxControls"",
                    ""action"": ""XboxA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""301c1ad5-2f66-41f7-a585-a7269375a283"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxControls"",
                    ""action"": ""XboxB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5956da7a-ff92-413a-9127-d98099f67c23"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxControls"",
                    ""action"": ""XboxX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5ef1ff2-a61a-49b3-92b9-f04a0006608f"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxControls"",
                    ""action"": ""XboxY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e45d8f63-9f37-46e9-9f6e-76f5eb379e6d"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxControls"",
                    ""action"": ""XboxLStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63b0dc18-6d5a-4019-8d06-cb7bf83ee08b"",
                    ""path"": ""<XInputController>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxControls"",
                    ""action"": ""XboxView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de32b3a2-247f-4c39-8165-4455f9fd7445"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxControls"",
                    ""action"": ""XboxMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6a02600-cf90-434e-8176-7c6ec4ba6320"",
                    ""path"": ""<SwitchProControllerHID>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SwitchControls"",
                    ""action"": ""SwitchA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0beb58e0-4cab-42ad-8cc2-ae88669c43b6"",
                    ""path"": ""<SwitchProControllerHID>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SwitchControls"",
                    ""action"": ""SwitchB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""210159b0-3b1a-48c2-a759-e7041cd07cc2"",
                    ""path"": ""<SwitchProControllerHID>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SwitchControls"",
                    ""action"": ""SwitchX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2def1858-3349-4cfc-abdd-4d04cbba56c5"",
                    ""path"": ""<SwitchProControllerHID>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SwitchControls"",
                    ""action"": ""SwitchY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f92c437a-5573-48b2-ba27-b1de0546bf42"",
                    ""path"": ""<SwitchProControllerHID>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SwitchControls"",
                    ""action"": ""SwitchLStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""167cb053-977b-4fd7-b0c6-58ef44395734"",
                    ""path"": ""<SwitchProControllerHID>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SwitchControls"",
                    ""action"": ""SwitchMinus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1710bb8e-f2c1-4123-8b55-17cefe32ab96"",
                    ""path"": ""<SwitchProControllerHID>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SwitchControls"",
                    ""action"": ""SwitchPlus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42d3cbb6-c5c7-4fbf-83c0-90b49452a119"",
                    ""path"": ""<WebGLGamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebLStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2c72c13-9e3f-45bb-a440-b14fcccd7a80"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d69c2a25-eca0-4783-b590-d03cec44b515"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2100840-44fe-4c67-8ab6-2436935d449b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70d280e1-0761-45f7-8f1f-821c8f17b35d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abca6638-a729-4d4c-a8f6-80759abd68e6"",
                    ""path"": ""<WebGLGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebLShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1940060-9924-48d2-aa0a-535f72dc3a15"",
                    ""path"": ""<WebGLGamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebRStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4aaf2ca6-7c47-4293-a110-fec6ffbc415f"",
                    ""path"": ""<WebGLGamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7caf4bc0-7ce8-4584-ae3a-eaa2b3048a1f"",
                    ""path"": ""<WebGLGamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""WebGLControls"",
                    ""action"": ""WebLStickUpwards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc75bcd8-7a9e-4808-8452-155a7b961570"",
                    ""path"": ""<DualShockGamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlaystationControls"",
                    ""action"": ""PlaystationLStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9ebdc17-ddb9-4a7b-9628-61677bfddf66"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlaystationControls"",
                    ""action"": ""PlaystationCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8998ac5d-9c1d-4e44-8e1c-7244498811e0"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlaystationControls"",
                    ""action"": ""PlaystationTriangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5191c508-8d91-47c1-8686-c0885e75bc1b"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlaystationControls"",
                    ""action"": ""PlaystationCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bc51ffc-a4ac-47e7-840e-f9ac33cf25c3"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlaystationControls"",
                    ""action"": ""PlaystationSquare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddeaec2c-f8c0-4bce-ae3d-0b7197c9dbba"",
                    ""path"": ""<DualShockGamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlaystationControls"",
                    ""action"": ""PlaystationShare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cfff374-22dc-4be3-a45d-13a04c60cfd9"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PlaystationControls"",
                    ""action"": ""PlaystationOptions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""XboxControls"",
            ""bindingGroup"": ""XboxControls"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""SwitchControls"",
            ""bindingGroup"": ""SwitchControls"",
            ""devices"": [
                {
                    ""devicePath"": ""<SwitchProControllerHID>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""WebGLControls"",
            ""bindingGroup"": ""WebGLControls"",
            ""devices"": [
                {
                    ""devicePath"": ""<WebGLGamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""PlaystationControls"",
            ""bindingGroup"": ""PlaystationControls"",
            ""devices"": [
                {
                    ""devicePath"": ""<DualShockGamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // ControlBinds
        m_ControlBinds = asset.FindActionMap("ControlBinds", throwIfNotFound: true);
        m_ControlBinds_KeyboardLStick = m_ControlBinds.FindAction("KeyboardLStick", throwIfNotFound: true);
        m_ControlBinds_KeyboardEnter = m_ControlBinds.FindAction("KeyboardEnter", throwIfNotFound: true);
        m_ControlBinds_KeyboardLShift = m_ControlBinds.FindAction("KeyboardLShift", throwIfNotFound: true);
        m_ControlBinds_KeyboardEscape = m_ControlBinds.FindAction("KeyboardEscape", throwIfNotFound: true);
        m_ControlBinds_KeyboardSpace = m_ControlBinds.FindAction("KeyboardSpace", throwIfNotFound: true);
        m_ControlBinds_KeyboardQ = m_ControlBinds.FindAction("KeyboardQ", throwIfNotFound: true);
        m_ControlBinds_KeyboardE = m_ControlBinds.FindAction("KeyboardE", throwIfNotFound: true);
        m_ControlBinds_KeyboardR = m_ControlBinds.FindAction("KeyboardR", throwIfNotFound: true);
        m_ControlBinds_XboxA = m_ControlBinds.FindAction("XboxA", throwIfNotFound: true);
        m_ControlBinds_XboxB = m_ControlBinds.FindAction("XboxB", throwIfNotFound: true);
        m_ControlBinds_XboxX = m_ControlBinds.FindAction("XboxX", throwIfNotFound: true);
        m_ControlBinds_XboxY = m_ControlBinds.FindAction("XboxY", throwIfNotFound: true);
        m_ControlBinds_XboxLStick = m_ControlBinds.FindAction("XboxLStick", throwIfNotFound: true);
        m_ControlBinds_XboxView = m_ControlBinds.FindAction("XboxView", throwIfNotFound: true);
        m_ControlBinds_XboxMenu = m_ControlBinds.FindAction("XboxMenu", throwIfNotFound: true);
        m_ControlBinds_SwitchA = m_ControlBinds.FindAction("SwitchA", throwIfNotFound: true);
        m_ControlBinds_SwitchB = m_ControlBinds.FindAction("SwitchB", throwIfNotFound: true);
        m_ControlBinds_SwitchX = m_ControlBinds.FindAction("SwitchX", throwIfNotFound: true);
        m_ControlBinds_SwitchY = m_ControlBinds.FindAction("SwitchY", throwIfNotFound: true);
        m_ControlBinds_SwitchLStick = m_ControlBinds.FindAction("SwitchLStick", throwIfNotFound: true);
        m_ControlBinds_SwitchMinus = m_ControlBinds.FindAction("SwitchMinus", throwIfNotFound: true);
        m_ControlBinds_SwitchPlus = m_ControlBinds.FindAction("SwitchPlus", throwIfNotFound: true);
        m_ControlBinds_WebLStick = m_ControlBinds.FindAction("WebLStick", throwIfNotFound: true);
        m_ControlBinds_WebEast = m_ControlBinds.FindAction("WebEast", throwIfNotFound: true);
        m_ControlBinds_WebSouth = m_ControlBinds.FindAction("WebSouth", throwIfNotFound: true);
        m_ControlBinds_WebNorth = m_ControlBinds.FindAction("WebNorth", throwIfNotFound: true);
        m_ControlBinds_WebWest = m_ControlBinds.FindAction("WebWest", throwIfNotFound: true);
        m_ControlBinds_WebLShoulder = m_ControlBinds.FindAction("WebLShoulder", throwIfNotFound: true);
        m_ControlBinds_WebRStickPress = m_ControlBinds.FindAction("WebRStickPress", throwIfNotFound: true);
        m_ControlBinds_WebSelect = m_ControlBinds.FindAction("WebSelect", throwIfNotFound: true);
        m_ControlBinds_WebLStickUpwards = m_ControlBinds.FindAction("WebLStickUpwards", throwIfNotFound: true);
        m_ControlBinds_PlaystationLStick = m_ControlBinds.FindAction("PlaystationLStick", throwIfNotFound: true);
        m_ControlBinds_PlaystationCross = m_ControlBinds.FindAction("PlaystationCross", throwIfNotFound: true);
        m_ControlBinds_PlaystationTriangle = m_ControlBinds.FindAction("PlaystationTriangle", throwIfNotFound: true);
        m_ControlBinds_PlaystationCircle = m_ControlBinds.FindAction("PlaystationCircle", throwIfNotFound: true);
        m_ControlBinds_PlaystationSquare = m_ControlBinds.FindAction("PlaystationSquare", throwIfNotFound: true);
        m_ControlBinds_PlaystationShare = m_ControlBinds.FindAction("PlaystationShare", throwIfNotFound: true);
        m_ControlBinds_PlaystationOptions = m_ControlBinds.FindAction("PlaystationOptions", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControlBinds
    private readonly InputActionMap m_ControlBinds;
    private List<IControlBindsActions> m_ControlBindsActionsCallbackInterfaces = new List<IControlBindsActions>();
    private readonly InputAction m_ControlBinds_KeyboardLStick;
    private readonly InputAction m_ControlBinds_KeyboardEnter;
    private readonly InputAction m_ControlBinds_KeyboardLShift;
    private readonly InputAction m_ControlBinds_KeyboardEscape;
    private readonly InputAction m_ControlBinds_KeyboardSpace;
    private readonly InputAction m_ControlBinds_KeyboardQ;
    private readonly InputAction m_ControlBinds_KeyboardE;
    private readonly InputAction m_ControlBinds_KeyboardR;
    private readonly InputAction m_ControlBinds_XboxA;
    private readonly InputAction m_ControlBinds_XboxB;
    private readonly InputAction m_ControlBinds_XboxX;
    private readonly InputAction m_ControlBinds_XboxY;
    private readonly InputAction m_ControlBinds_XboxLStick;
    private readonly InputAction m_ControlBinds_XboxView;
    private readonly InputAction m_ControlBinds_XboxMenu;
    private readonly InputAction m_ControlBinds_SwitchA;
    private readonly InputAction m_ControlBinds_SwitchB;
    private readonly InputAction m_ControlBinds_SwitchX;
    private readonly InputAction m_ControlBinds_SwitchY;
    private readonly InputAction m_ControlBinds_SwitchLStick;
    private readonly InputAction m_ControlBinds_SwitchMinus;
    private readonly InputAction m_ControlBinds_SwitchPlus;
    private readonly InputAction m_ControlBinds_WebLStick;
    private readonly InputAction m_ControlBinds_WebEast;
    private readonly InputAction m_ControlBinds_WebSouth;
    private readonly InputAction m_ControlBinds_WebNorth;
    private readonly InputAction m_ControlBinds_WebWest;
    private readonly InputAction m_ControlBinds_WebLShoulder;
    private readonly InputAction m_ControlBinds_WebRStickPress;
    private readonly InputAction m_ControlBinds_WebSelect;
    private readonly InputAction m_ControlBinds_WebLStickUpwards;
    private readonly InputAction m_ControlBinds_PlaystationLStick;
    private readonly InputAction m_ControlBinds_PlaystationCross;
    private readonly InputAction m_ControlBinds_PlaystationTriangle;
    private readonly InputAction m_ControlBinds_PlaystationCircle;
    private readonly InputAction m_ControlBinds_PlaystationSquare;
    private readonly InputAction m_ControlBinds_PlaystationShare;
    private readonly InputAction m_ControlBinds_PlaystationOptions;
    public struct ControlBindsActions
    {
        private @PlayerControls m_Wrapper;
        public ControlBindsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @KeyboardLStick => m_Wrapper.m_ControlBinds_KeyboardLStick;
        public InputAction @KeyboardEnter => m_Wrapper.m_ControlBinds_KeyboardEnter;
        public InputAction @KeyboardLShift => m_Wrapper.m_ControlBinds_KeyboardLShift;
        public InputAction @KeyboardEscape => m_Wrapper.m_ControlBinds_KeyboardEscape;
        public InputAction @KeyboardSpace => m_Wrapper.m_ControlBinds_KeyboardSpace;
        public InputAction @KeyboardQ => m_Wrapper.m_ControlBinds_KeyboardQ;
        public InputAction @KeyboardE => m_Wrapper.m_ControlBinds_KeyboardE;
        public InputAction @KeyboardR => m_Wrapper.m_ControlBinds_KeyboardR;
        public InputAction @XboxA => m_Wrapper.m_ControlBinds_XboxA;
        public InputAction @XboxB => m_Wrapper.m_ControlBinds_XboxB;
        public InputAction @XboxX => m_Wrapper.m_ControlBinds_XboxX;
        public InputAction @XboxY => m_Wrapper.m_ControlBinds_XboxY;
        public InputAction @XboxLStick => m_Wrapper.m_ControlBinds_XboxLStick;
        public InputAction @XboxView => m_Wrapper.m_ControlBinds_XboxView;
        public InputAction @XboxMenu => m_Wrapper.m_ControlBinds_XboxMenu;
        public InputAction @SwitchA => m_Wrapper.m_ControlBinds_SwitchA;
        public InputAction @SwitchB => m_Wrapper.m_ControlBinds_SwitchB;
        public InputAction @SwitchX => m_Wrapper.m_ControlBinds_SwitchX;
        public InputAction @SwitchY => m_Wrapper.m_ControlBinds_SwitchY;
        public InputAction @SwitchLStick => m_Wrapper.m_ControlBinds_SwitchLStick;
        public InputAction @SwitchMinus => m_Wrapper.m_ControlBinds_SwitchMinus;
        public InputAction @SwitchPlus => m_Wrapper.m_ControlBinds_SwitchPlus;
        public InputAction @WebLStick => m_Wrapper.m_ControlBinds_WebLStick;
        public InputAction @WebEast => m_Wrapper.m_ControlBinds_WebEast;
        public InputAction @WebSouth => m_Wrapper.m_ControlBinds_WebSouth;
        public InputAction @WebNorth => m_Wrapper.m_ControlBinds_WebNorth;
        public InputAction @WebWest => m_Wrapper.m_ControlBinds_WebWest;
        public InputAction @WebLShoulder => m_Wrapper.m_ControlBinds_WebLShoulder;
        public InputAction @WebRStickPress => m_Wrapper.m_ControlBinds_WebRStickPress;
        public InputAction @WebSelect => m_Wrapper.m_ControlBinds_WebSelect;
        public InputAction @WebLStickUpwards => m_Wrapper.m_ControlBinds_WebLStickUpwards;
        public InputAction @PlaystationLStick => m_Wrapper.m_ControlBinds_PlaystationLStick;
        public InputAction @PlaystationCross => m_Wrapper.m_ControlBinds_PlaystationCross;
        public InputAction @PlaystationTriangle => m_Wrapper.m_ControlBinds_PlaystationTriangle;
        public InputAction @PlaystationCircle => m_Wrapper.m_ControlBinds_PlaystationCircle;
        public InputAction @PlaystationSquare => m_Wrapper.m_ControlBinds_PlaystationSquare;
        public InputAction @PlaystationShare => m_Wrapper.m_ControlBinds_PlaystationShare;
        public InputAction @PlaystationOptions => m_Wrapper.m_ControlBinds_PlaystationOptions;
        public InputActionMap Get() { return m_Wrapper.m_ControlBinds; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlBindsActions set) { return set.Get(); }
        public void AddCallbacks(IControlBindsActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlBindsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlBindsActionsCallbackInterfaces.Add(instance);
            @KeyboardLStick.started += instance.OnKeyboardLStick;
            @KeyboardLStick.performed += instance.OnKeyboardLStick;
            @KeyboardLStick.canceled += instance.OnKeyboardLStick;
            @KeyboardEnter.started += instance.OnKeyboardEnter;
            @KeyboardEnter.performed += instance.OnKeyboardEnter;
            @KeyboardEnter.canceled += instance.OnKeyboardEnter;
            @KeyboardLShift.started += instance.OnKeyboardLShift;
            @KeyboardLShift.performed += instance.OnKeyboardLShift;
            @KeyboardLShift.canceled += instance.OnKeyboardLShift;
            @KeyboardEscape.started += instance.OnKeyboardEscape;
            @KeyboardEscape.performed += instance.OnKeyboardEscape;
            @KeyboardEscape.canceled += instance.OnKeyboardEscape;
            @KeyboardSpace.started += instance.OnKeyboardSpace;
            @KeyboardSpace.performed += instance.OnKeyboardSpace;
            @KeyboardSpace.canceled += instance.OnKeyboardSpace;
            @KeyboardQ.started += instance.OnKeyboardQ;
            @KeyboardQ.performed += instance.OnKeyboardQ;
            @KeyboardQ.canceled += instance.OnKeyboardQ;
            @KeyboardE.started += instance.OnKeyboardE;
            @KeyboardE.performed += instance.OnKeyboardE;
            @KeyboardE.canceled += instance.OnKeyboardE;
            @KeyboardR.started += instance.OnKeyboardR;
            @KeyboardR.performed += instance.OnKeyboardR;
            @KeyboardR.canceled += instance.OnKeyboardR;
            @XboxA.started += instance.OnXboxA;
            @XboxA.performed += instance.OnXboxA;
            @XboxA.canceled += instance.OnXboxA;
            @XboxB.started += instance.OnXboxB;
            @XboxB.performed += instance.OnXboxB;
            @XboxB.canceled += instance.OnXboxB;
            @XboxX.started += instance.OnXboxX;
            @XboxX.performed += instance.OnXboxX;
            @XboxX.canceled += instance.OnXboxX;
            @XboxY.started += instance.OnXboxY;
            @XboxY.performed += instance.OnXboxY;
            @XboxY.canceled += instance.OnXboxY;
            @XboxLStick.started += instance.OnXboxLStick;
            @XboxLStick.performed += instance.OnXboxLStick;
            @XboxLStick.canceled += instance.OnXboxLStick;
            @XboxView.started += instance.OnXboxView;
            @XboxView.performed += instance.OnXboxView;
            @XboxView.canceled += instance.OnXboxView;
            @XboxMenu.started += instance.OnXboxMenu;
            @XboxMenu.performed += instance.OnXboxMenu;
            @XboxMenu.canceled += instance.OnXboxMenu;
            @SwitchA.started += instance.OnSwitchA;
            @SwitchA.performed += instance.OnSwitchA;
            @SwitchA.canceled += instance.OnSwitchA;
            @SwitchB.started += instance.OnSwitchB;
            @SwitchB.performed += instance.OnSwitchB;
            @SwitchB.canceled += instance.OnSwitchB;
            @SwitchX.started += instance.OnSwitchX;
            @SwitchX.performed += instance.OnSwitchX;
            @SwitchX.canceled += instance.OnSwitchX;
            @SwitchY.started += instance.OnSwitchY;
            @SwitchY.performed += instance.OnSwitchY;
            @SwitchY.canceled += instance.OnSwitchY;
            @SwitchLStick.started += instance.OnSwitchLStick;
            @SwitchLStick.performed += instance.OnSwitchLStick;
            @SwitchLStick.canceled += instance.OnSwitchLStick;
            @SwitchMinus.started += instance.OnSwitchMinus;
            @SwitchMinus.performed += instance.OnSwitchMinus;
            @SwitchMinus.canceled += instance.OnSwitchMinus;
            @SwitchPlus.started += instance.OnSwitchPlus;
            @SwitchPlus.performed += instance.OnSwitchPlus;
            @SwitchPlus.canceled += instance.OnSwitchPlus;
            @WebLStick.started += instance.OnWebLStick;
            @WebLStick.performed += instance.OnWebLStick;
            @WebLStick.canceled += instance.OnWebLStick;
            @WebEast.started += instance.OnWebEast;
            @WebEast.performed += instance.OnWebEast;
            @WebEast.canceled += instance.OnWebEast;
            @WebSouth.started += instance.OnWebSouth;
            @WebSouth.performed += instance.OnWebSouth;
            @WebSouth.canceled += instance.OnWebSouth;
            @WebNorth.started += instance.OnWebNorth;
            @WebNorth.performed += instance.OnWebNorth;
            @WebNorth.canceled += instance.OnWebNorth;
            @WebWest.started += instance.OnWebWest;
            @WebWest.performed += instance.OnWebWest;
            @WebWest.canceled += instance.OnWebWest;
            @WebLShoulder.started += instance.OnWebLShoulder;
            @WebLShoulder.performed += instance.OnWebLShoulder;
            @WebLShoulder.canceled += instance.OnWebLShoulder;
            @WebRStickPress.started += instance.OnWebRStickPress;
            @WebRStickPress.performed += instance.OnWebRStickPress;
            @WebRStickPress.canceled += instance.OnWebRStickPress;
            @WebSelect.started += instance.OnWebSelect;
            @WebSelect.performed += instance.OnWebSelect;
            @WebSelect.canceled += instance.OnWebSelect;
            @WebLStickUpwards.started += instance.OnWebLStickUpwards;
            @WebLStickUpwards.performed += instance.OnWebLStickUpwards;
            @WebLStickUpwards.canceled += instance.OnWebLStickUpwards;
            @PlaystationLStick.started += instance.OnPlaystationLStick;
            @PlaystationLStick.performed += instance.OnPlaystationLStick;
            @PlaystationLStick.canceled += instance.OnPlaystationLStick;
            @PlaystationCross.started += instance.OnPlaystationCross;
            @PlaystationCross.performed += instance.OnPlaystationCross;
            @PlaystationCross.canceled += instance.OnPlaystationCross;
            @PlaystationTriangle.started += instance.OnPlaystationTriangle;
            @PlaystationTriangle.performed += instance.OnPlaystationTriangle;
            @PlaystationTriangle.canceled += instance.OnPlaystationTriangle;
            @PlaystationCircle.started += instance.OnPlaystationCircle;
            @PlaystationCircle.performed += instance.OnPlaystationCircle;
            @PlaystationCircle.canceled += instance.OnPlaystationCircle;
            @PlaystationSquare.started += instance.OnPlaystationSquare;
            @PlaystationSquare.performed += instance.OnPlaystationSquare;
            @PlaystationSquare.canceled += instance.OnPlaystationSquare;
            @PlaystationShare.started += instance.OnPlaystationShare;
            @PlaystationShare.performed += instance.OnPlaystationShare;
            @PlaystationShare.canceled += instance.OnPlaystationShare;
            @PlaystationOptions.started += instance.OnPlaystationOptions;
            @PlaystationOptions.performed += instance.OnPlaystationOptions;
            @PlaystationOptions.canceled += instance.OnPlaystationOptions;
        }

        private void UnregisterCallbacks(IControlBindsActions instance)
        {
            @KeyboardLStick.started -= instance.OnKeyboardLStick;
            @KeyboardLStick.performed -= instance.OnKeyboardLStick;
            @KeyboardLStick.canceled -= instance.OnKeyboardLStick;
            @KeyboardEnter.started -= instance.OnKeyboardEnter;
            @KeyboardEnter.performed -= instance.OnKeyboardEnter;
            @KeyboardEnter.canceled -= instance.OnKeyboardEnter;
            @KeyboardLShift.started -= instance.OnKeyboardLShift;
            @KeyboardLShift.performed -= instance.OnKeyboardLShift;
            @KeyboardLShift.canceled -= instance.OnKeyboardLShift;
            @KeyboardEscape.started -= instance.OnKeyboardEscape;
            @KeyboardEscape.performed -= instance.OnKeyboardEscape;
            @KeyboardEscape.canceled -= instance.OnKeyboardEscape;
            @KeyboardSpace.started -= instance.OnKeyboardSpace;
            @KeyboardSpace.performed -= instance.OnKeyboardSpace;
            @KeyboardSpace.canceled -= instance.OnKeyboardSpace;
            @KeyboardQ.started -= instance.OnKeyboardQ;
            @KeyboardQ.performed -= instance.OnKeyboardQ;
            @KeyboardQ.canceled -= instance.OnKeyboardQ;
            @KeyboardE.started -= instance.OnKeyboardE;
            @KeyboardE.performed -= instance.OnKeyboardE;
            @KeyboardE.canceled -= instance.OnKeyboardE;
            @KeyboardR.started -= instance.OnKeyboardR;
            @KeyboardR.performed -= instance.OnKeyboardR;
            @KeyboardR.canceled -= instance.OnKeyboardR;
            @XboxA.started -= instance.OnXboxA;
            @XboxA.performed -= instance.OnXboxA;
            @XboxA.canceled -= instance.OnXboxA;
            @XboxB.started -= instance.OnXboxB;
            @XboxB.performed -= instance.OnXboxB;
            @XboxB.canceled -= instance.OnXboxB;
            @XboxX.started -= instance.OnXboxX;
            @XboxX.performed -= instance.OnXboxX;
            @XboxX.canceled -= instance.OnXboxX;
            @XboxY.started -= instance.OnXboxY;
            @XboxY.performed -= instance.OnXboxY;
            @XboxY.canceled -= instance.OnXboxY;
            @XboxLStick.started -= instance.OnXboxLStick;
            @XboxLStick.performed -= instance.OnXboxLStick;
            @XboxLStick.canceled -= instance.OnXboxLStick;
            @XboxView.started -= instance.OnXboxView;
            @XboxView.performed -= instance.OnXboxView;
            @XboxView.canceled -= instance.OnXboxView;
            @XboxMenu.started -= instance.OnXboxMenu;
            @XboxMenu.performed -= instance.OnXboxMenu;
            @XboxMenu.canceled -= instance.OnXboxMenu;
            @SwitchA.started -= instance.OnSwitchA;
            @SwitchA.performed -= instance.OnSwitchA;
            @SwitchA.canceled -= instance.OnSwitchA;
            @SwitchB.started -= instance.OnSwitchB;
            @SwitchB.performed -= instance.OnSwitchB;
            @SwitchB.canceled -= instance.OnSwitchB;
            @SwitchX.started -= instance.OnSwitchX;
            @SwitchX.performed -= instance.OnSwitchX;
            @SwitchX.canceled -= instance.OnSwitchX;
            @SwitchY.started -= instance.OnSwitchY;
            @SwitchY.performed -= instance.OnSwitchY;
            @SwitchY.canceled -= instance.OnSwitchY;
            @SwitchLStick.started -= instance.OnSwitchLStick;
            @SwitchLStick.performed -= instance.OnSwitchLStick;
            @SwitchLStick.canceled -= instance.OnSwitchLStick;
            @SwitchMinus.started -= instance.OnSwitchMinus;
            @SwitchMinus.performed -= instance.OnSwitchMinus;
            @SwitchMinus.canceled -= instance.OnSwitchMinus;
            @SwitchPlus.started -= instance.OnSwitchPlus;
            @SwitchPlus.performed -= instance.OnSwitchPlus;
            @SwitchPlus.canceled -= instance.OnSwitchPlus;
            @WebLStick.started -= instance.OnWebLStick;
            @WebLStick.performed -= instance.OnWebLStick;
            @WebLStick.canceled -= instance.OnWebLStick;
            @WebEast.started -= instance.OnWebEast;
            @WebEast.performed -= instance.OnWebEast;
            @WebEast.canceled -= instance.OnWebEast;
            @WebSouth.started -= instance.OnWebSouth;
            @WebSouth.performed -= instance.OnWebSouth;
            @WebSouth.canceled -= instance.OnWebSouth;
            @WebNorth.started -= instance.OnWebNorth;
            @WebNorth.performed -= instance.OnWebNorth;
            @WebNorth.canceled -= instance.OnWebNorth;
            @WebWest.started -= instance.OnWebWest;
            @WebWest.performed -= instance.OnWebWest;
            @WebWest.canceled -= instance.OnWebWest;
            @WebLShoulder.started -= instance.OnWebLShoulder;
            @WebLShoulder.performed -= instance.OnWebLShoulder;
            @WebLShoulder.canceled -= instance.OnWebLShoulder;
            @WebRStickPress.started -= instance.OnWebRStickPress;
            @WebRStickPress.performed -= instance.OnWebRStickPress;
            @WebRStickPress.canceled -= instance.OnWebRStickPress;
            @WebSelect.started -= instance.OnWebSelect;
            @WebSelect.performed -= instance.OnWebSelect;
            @WebSelect.canceled -= instance.OnWebSelect;
            @WebLStickUpwards.started -= instance.OnWebLStickUpwards;
            @WebLStickUpwards.performed -= instance.OnWebLStickUpwards;
            @WebLStickUpwards.canceled -= instance.OnWebLStickUpwards;
            @PlaystationLStick.started -= instance.OnPlaystationLStick;
            @PlaystationLStick.performed -= instance.OnPlaystationLStick;
            @PlaystationLStick.canceled -= instance.OnPlaystationLStick;
            @PlaystationCross.started -= instance.OnPlaystationCross;
            @PlaystationCross.performed -= instance.OnPlaystationCross;
            @PlaystationCross.canceled -= instance.OnPlaystationCross;
            @PlaystationTriangle.started -= instance.OnPlaystationTriangle;
            @PlaystationTriangle.performed -= instance.OnPlaystationTriangle;
            @PlaystationTriangle.canceled -= instance.OnPlaystationTriangle;
            @PlaystationCircle.started -= instance.OnPlaystationCircle;
            @PlaystationCircle.performed -= instance.OnPlaystationCircle;
            @PlaystationCircle.canceled -= instance.OnPlaystationCircle;
            @PlaystationSquare.started -= instance.OnPlaystationSquare;
            @PlaystationSquare.performed -= instance.OnPlaystationSquare;
            @PlaystationSquare.canceled -= instance.OnPlaystationSquare;
            @PlaystationShare.started -= instance.OnPlaystationShare;
            @PlaystationShare.performed -= instance.OnPlaystationShare;
            @PlaystationShare.canceled -= instance.OnPlaystationShare;
            @PlaystationOptions.started -= instance.OnPlaystationOptions;
            @PlaystationOptions.performed -= instance.OnPlaystationOptions;
            @PlaystationOptions.canceled -= instance.OnPlaystationOptions;
        }

        public void RemoveCallbacks(IControlBindsActions instance)
        {
            if (m_Wrapper.m_ControlBindsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlBindsActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlBindsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlBindsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlBindsActions @ControlBinds => new ControlBindsActions(this);
    private int m_XboxControlsSchemeIndex = -1;
    public InputControlScheme XboxControlsScheme
    {
        get
        {
            if (m_XboxControlsSchemeIndex == -1) m_XboxControlsSchemeIndex = asset.FindControlSchemeIndex("XboxControls");
            return asset.controlSchemes[m_XboxControlsSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_SwitchControlsSchemeIndex = -1;
    public InputControlScheme SwitchControlsScheme
    {
        get
        {
            if (m_SwitchControlsSchemeIndex == -1) m_SwitchControlsSchemeIndex = asset.FindControlSchemeIndex("SwitchControls");
            return asset.controlSchemes[m_SwitchControlsSchemeIndex];
        }
    }
    private int m_WebGLControlsSchemeIndex = -1;
    public InputControlScheme WebGLControlsScheme
    {
        get
        {
            if (m_WebGLControlsSchemeIndex == -1) m_WebGLControlsSchemeIndex = asset.FindControlSchemeIndex("WebGLControls");
            return asset.controlSchemes[m_WebGLControlsSchemeIndex];
        }
    }
    private int m_PlaystationControlsSchemeIndex = -1;
    public InputControlScheme PlaystationControlsScheme
    {
        get
        {
            if (m_PlaystationControlsSchemeIndex == -1) m_PlaystationControlsSchemeIndex = asset.FindControlSchemeIndex("PlaystationControls");
            return asset.controlSchemes[m_PlaystationControlsSchemeIndex];
        }
    }
    public interface IControlBindsActions
    {
        void OnKeyboardLStick(InputAction.CallbackContext context);
        void OnKeyboardEnter(InputAction.CallbackContext context);
        void OnKeyboardLShift(InputAction.CallbackContext context);
        void OnKeyboardEscape(InputAction.CallbackContext context);
        void OnKeyboardSpace(InputAction.CallbackContext context);
        void OnKeyboardQ(InputAction.CallbackContext context);
        void OnKeyboardE(InputAction.CallbackContext context);
        void OnKeyboardR(InputAction.CallbackContext context);
        void OnXboxA(InputAction.CallbackContext context);
        void OnXboxB(InputAction.CallbackContext context);
        void OnXboxX(InputAction.CallbackContext context);
        void OnXboxY(InputAction.CallbackContext context);
        void OnXboxLStick(InputAction.CallbackContext context);
        void OnXboxView(InputAction.CallbackContext context);
        void OnXboxMenu(InputAction.CallbackContext context);
        void OnSwitchA(InputAction.CallbackContext context);
        void OnSwitchB(InputAction.CallbackContext context);
        void OnSwitchX(InputAction.CallbackContext context);
        void OnSwitchY(InputAction.CallbackContext context);
        void OnSwitchLStick(InputAction.CallbackContext context);
        void OnSwitchMinus(InputAction.CallbackContext context);
        void OnSwitchPlus(InputAction.CallbackContext context);
        void OnWebLStick(InputAction.CallbackContext context);
        void OnWebEast(InputAction.CallbackContext context);
        void OnWebSouth(InputAction.CallbackContext context);
        void OnWebNorth(InputAction.CallbackContext context);
        void OnWebWest(InputAction.CallbackContext context);
        void OnWebLShoulder(InputAction.CallbackContext context);
        void OnWebRStickPress(InputAction.CallbackContext context);
        void OnWebSelect(InputAction.CallbackContext context);
        void OnWebLStickUpwards(InputAction.CallbackContext context);
        void OnPlaystationLStick(InputAction.CallbackContext context);
        void OnPlaystationCross(InputAction.CallbackContext context);
        void OnPlaystationTriangle(InputAction.CallbackContext context);
        void OnPlaystationCircle(InputAction.CallbackContext context);
        void OnPlaystationSquare(InputAction.CallbackContext context);
        void OnPlaystationShare(InputAction.CallbackContext context);
        void OnPlaystationOptions(InputAction.CallbackContext context);
    }
}
